/**
 * Generates src/icons.js (base64 PNGs) from scripts/icons/*.png.
 * Run `npm run icons` after changing an image.
 */
const fs = require('node:fs')
const path = require('node:path')

const dir = path.join(__dirname, 'icons')
const out = path.join(__dirname, '..', 'src', 'icons.js')
const icons = {}
for (const file of fs.readdirSync(dir).sort()) {
	if (!file.endsWith('.png')) continue
	icons[path.basename(file, '.png')] = fs.readFileSync(path.join(dir, file)).toString('base64')
}
const body = Object.entries(icons)
	.map(([k, v]) => `\t${k}: '${v}',`)
	.join('\n')
fs.writeFileSync(
	out,
	`// Generated by scripts/build-icons.js – do not edit.\nconst icons = {\n${body}\n}\n\nmodule.exports = { icons }\n`,
)
console.log(`wrote ${out} (${Object.keys(icons).length} icons)`)
